
/**
 * Generates deterministic output for the Data Agent based on input.
 */
export const generateDataOutput = (input: string) => {
    return [
        `• Monad executes transactions in parallel (optimistic execution) while maintaining sequential consistency.`,
        `• High performance: Target of 10,000 TPS with 1-second block times.`,
        `• Full EVM Compatibility: Bytecode-level compatibility allows existing Ethereum dApps to deploy seamlessly.`,
        `• Database Optimization: MonadDb uses asynchronous IO to remove bottlenecks in state access.`,
        `• Context: User query '${input}' relates to high-throughput DeFi and Agent infrastructure.`
    ].join('\n');
};

/**
 * Generates deterministic SEO output.
 */
export const generateSeoOutput = (input: string) => {
    const keywords = input.split(' ').slice(0, 3).join(', ');
    return [
        `Title: Ultimate Guide to Monad Blockchain: ${input}`,
        `Meta Description: Discover how Monad scales Ethereum with parallel execution. Relevant for: ${keywords}.`,
        `H2: What is Monad?`,
        `H2: Understanding Parallel Execution`,
        `H2: MonadDb vs LevelDB`,
        `H2: The ${keywords} Use Case`,
        `H2: Future of High-Performance EVM`
    ].join('\n');
};

/**
 * Generates final report (Formatting Agent).
 */
export const generateFinalReport = (input: string, dataOut: string, seoOut: string) => {
    return `
# RESEARCH REPORT: ${input}

## ${seoOut.split('\n')[0]}

${seoOut.split('\n')[1]}

---
### Key Findings
${dataOut}

---
### Content Structure
${seoOut.split('\n').filter(l => l.startsWith('H2')).map(l => `- ${l.replace('H2: ', '')}`).join('\n')}

*Generated by ClawWorks Agent Swarm*
    `.trim();
};
